
context("AllClasses-Prior")

n.test <- 5
test.identity <- FALSE
test.extended <- FALSE


test_that("Prior classes have correct value for iMethodPrior", {
    x <- new("ExchFixed")
    expect_identical(x@iMethodPrior, 0L)
    x <- new("ExchNormZero")
    expect_identical(x@iMethodPrior, 1L)
    x <- new("ExchNormCov")
    expect_identical(x@iMethodPrior, 2L)
    x <- new("ExchRobustZero")
    expect_identical(x@iMethodPrior, 3L)
    x <- new("ExchRobustCov")
    expect_identical(x@iMethodPrior, 4L)
    x <- new("DLMNoTrendNormZeroNoSeason")
    expect_identical(x@iMethodPrior, 5L)
    x <- new("DLMNoTrendNormZeroWithSeason")
    expect_identical(x@iMethodPrior, 6L)
    x <- new("DLMNoTrendNormCovNoSeason")
    expect_identical(x@iMethodPrior, 7L)
    x <- new("DLMNoTrendNormCovWithSeason")
    expect_identical(x@iMethodPrior, 8L)
    x <- new("DLMNoTrendRobustZeroNoSeason")
    expect_identical(x@iMethodPrior, 9L)
    x <- new("DLMNoTrendRobustZeroWithSeason")
    expect_identical(x@iMethodPrior, 10L)
    x <- new("DLMNoTrendRobustCovNoSeason")
    expect_identical(x@iMethodPrior, 11L)
    x <- new("DLMNoTrendRobustCovWithSeason")
    expect_identical(x@iMethodPrior, 12L)
    x <- new("DLMWithTrendNormZeroNoSeason")
    expect_identical(x@iMethodPrior, 13L)
    x <- new("DLMWithTrendNormZeroWithSeason")
    expect_identical(x@iMethodPrior, 14L)
    x <- new("DLMWithTrendNormCovNoSeason")
    expect_identical(x@iMethodPrior, 15L)
    x <- new("DLMWithTrendNormCovWithSeason")
    expect_identical(x@iMethodPrior, 16L)
    x <- new("DLMWithTrendRobustZeroNoSeason")
    expect_identical(x@iMethodPrior, 17L)
    x <- new("DLMWithTrendRobustZeroWithSeason")
    expect_identical(x@iMethodPrior, 18L)
    x <- new("DLMWithTrendRobustCovNoSeason")
    expect_identical(x@iMethodPrior, 19L)
    x <- new("DLMWithTrendRobustCovWithSeason")
    expect_identical(x@iMethodPrior, 20L)
    x <- new("ICARNormZero")
    expect_identical(x@iMethodPrior, 21L)
    x <- new("ICARNormCov")
    expect_identical(x@iMethodPrior, 22L)
    x <- new("ICARRobustZero")
    expect_identical(x@iMethodPrior, 23L)
    x <- new("ICARRobustCov")
    expect_identical(x@iMethodPrior, 24L)
    x <- new("MoveNormZero")
    expect_identical(x@iMethodPrior, 25L)
    x <- new("MoveNormCov")
    expect_identical(x@iMethodPrior, 26L)
    x <- new("MoveRobustZero")
    expect_identical(x@iMethodPrior, 27L)
    x <- new("MoveRobustCov")
    expect_identical(x@iMethodPrior, 28L)
    x <- new("KnownCertain")
    expect_identical(x@iMethodPrior, 29L)
    x <- new("KnownUncertain")
    expect_identical(x@iMethodPrior, 30L)
})

